<h2>Seznam zbraní</h2>

<?php if (isset($_SESSION["loggedInUser"])) { ?>
    <a href="/zwa_projekt/new-gun.php">Přidat zbraň</a>
<?php } ?>

<table border = 1>
    <thead>
        <th>ID</th>
        <th>Jméno</th>
        <th>Typ</th>
        <th>Cena</th>
        <th>Obrázek</th>
        <?php if (isset($_SESSION["loggedInUser"])) { ?>
            <th>Akce</th>
        <?php } ?>
    </thead>
    <tbody>
        <?php
            foreach ($guns as $gun) {
        ?>
            <tr>
                <td><?= $gun["id"] ?></td>
                <td><?= $gun["Name"] ?></td>
                 <td><?= $gun["type"] ?></td>
                <td><?= $gun["Price"] ?></td>
                <td>
                    <?php if ($gun["img"] !== null) { ?>
                        <img 
                            src="<?= $gun["img"] ?>" 
                            width="100" 
                            height="100"
                        >
                    <?php } else { ?>
                        x
                    <?php } ?>
                </td>
                <!-- <?php if (isset($_SESSION["loggedInUser"])) { ?> -->
                <td>
                    <form method="GET">
                        <input type="hidden" name="id" value="<?= $gun["id"] ?>">
                        <button>Upravit</button>
                    </form>
                    <form method="POST">
                        <input type="hidden" name="id" value="<?= $gun["id"] ?>">
                        <button name="deletegun">Odstranit</button>
                    </form>
                </td>
                <!-- <?php } ?> -->
            </tr>
        <?php
            }
        ?>
    </tbody>
</table>