<h2>Přidání nové zbraně</h2>
<form method="POST" enctype="multipart/form-data">
    <div>
        <label for="name">Jméno</label>
        <input type="text" name="name" id="name" required>
    </div>
      <div>
        <label for="type">Typ</label>
        <input type="text" name="type" id="type" required>
    </div>
    <div>
        <label for="price">Cena</label>
        <input type="number" name="price" id="price" required>
    </div>
    <div>
        <label for="image">Obrázek</label>
        <input type="file" accept="image/*" name="image" id="image">
    </div>

    <button name="newgun">Přidat zbraň</button>
</form>