<h2>Přidání nového skinu</h2>

<form method="POST" enctype="multipart/form-data">
    <div>
        <label for="name">Jméno</label>
        <input type="text" name="name" id="name" required>
    </div>
    <div>
        <label for="price">Cena</label>
        <input type="number" name="price" id="price" required>
    </div>
    <div>
        <label for="type">Typ zbraně</label>
        <select name="type" id="type" required>
            <?php foreach ($type as $guntype): ?>
  <option value="<?= $guntype['id']?>"><?= htmlspecialchars($guntype['name']) ?></option>
  <?php endforeach;?>
</select>
    </div>
    <div>
        <label for="image">Obrázek</label>
        <input type="file" accept="image/*" name="image" id="image">
    </div>

    <button name="newskin">Přidat skin</button>
</form>