<h1>Registrace</h1>

<form method="POST" enctype="multipart/form-data">
    <div>
        <label for="username">Uživatelské jméno</label>
        <input type="text" name="username" id="username" required>
    </div>
    <div>
        <label for="password">Heslo</label>
        <input type="password" name="password" id="password" required>
    </div>
    <div>
        <label for="passwordConfirm">Heslo znovu</label>
        <input type="password" name="passwordConfirm" id="passwordConfirm" required>
    </div>
    <div>
        <label for="admin">Administrativní práva</label>
        <input type="tyniint" name="admin" id="admin" required>
    </div>

    <button name="registerForm">Registrovat se</button>
</form>