<h2>Seznam skinů</h2>

<?php if (isset($_SESSION["loggedInUser"])) { ?>
    <a href="/zwa_projekt/new-skin.php">Přidat skin</a>
<?php } ?>

<table border = 1>
    <thead>
        <th>ID</th>
        <th>Jméno</th>
        <th>Cena</th>
        <th>Typ</th>
        <th>Obrázek</th>
        <?php if (isset($_SESSION["loggedInUser"])) { ?>
            <th>Akce</th>
        <?php } ?>
    </thead>
    <tbody>
        <?php
            foreach ($skins as $skin) {
        ?>
            <tr>
                <td><?= $skin["id"] ?></td>
                <td><?= $skin["name"] ?></td>
                <td><?= $skin["price"] ?></td>
                <td><?= $skin["type_name"] ?></td>
                <td>
                    <?php if ($skin["img"] !== null) { ?>
                        <img 
                            src="<?= $skin["img"] ?>" 
                            width="100" 
                            height="100"
                        >
                    <?php } else { ?>
                        x
                    <?php } ?>
                </td>
                <!-- <?php if (isset($_SESSION["loggedInUser"])) { ?> -->
                <td>
                    <form method="GET">
                        <input type="hidden" name="id" value="<?= $skin["id"] ?>">
                        <button>Upravit</button>
                    </form>
                    <form method="POST">
                        <input type="hidden" name="id" value="<?= $skin["id"] ?>">
                        <button name="deleteskin">Odstranit</button>
                    </form>
                </td>
                <!-- <?php } ?> -->
            </tr>
        <?php
            }
        ?>
    </tbody>
</table>