-- MySQL Script generated by MySQL Workbench
-- Thu May 22 08:57:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projekt` DEFAULT CHARACTER SET utf8 ;
USE `projekt` ;

-- -----------------------------------------------------
-- Table `projekt`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `admin` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`guns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`guns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`skins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`skins` (
  `idskin` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`idskin`, `type`),
  INDEX `fk_skins_Guns_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_skins_Guns`
    FOREIGN KEY (`type`)
    REFERENCES `projekt`.`guns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`vlastnene skiny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`vlastnene skiny` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_skin` INT NOT NULL,
  PRIMARY KEY (`id`, `id_user`, `id_skin`),
  INDEX `fk_vlastnene skiny_Users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_vlastnene skiny_skins1_idx` (`id_skin` ASC) VISIBLE,
  CONSTRAINT `fk_vlastnene skiny_Users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `projekt`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vlastnene skiny_skins1`
    FOREIGN KEY (`id_skin`)
    REFERENCES `projekt`.`skins` (`idskin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
