<h2>Seznam skinů uživatulů</h2>

<?php if (isset($_SESSION["loggedInUser"])) { ?>
    <a href="/zwa_projekt/new-user_skin.php">Přidat skin</a>
<?php } ?>
<table border = 1>
 <thead>
        <th>ID</th>
        <th>uživatel</th>
        <th>skin</th>
         <?php if (isset($_SESSION["loggedInUser"])) { ?>
            <th>Akce</th>
        <?php } ?>
        </thead>
    <tbody>
        <?php
            foreach ($uskins as $uskin) {
        ?>
            <tr>
<td><?= $uskin["id"] ?></td>
<td><?= $uskin["user_name"] ?></td>
<td><?= $uskin["skin_name"] ?></td>
            </tr>
                </td>
                <!-- <?php if (isset($_SESSION["loggedInUser"])) { ?> -->
                <td>
                    <form method="GET">
                        <input type="hidden" name="id" value="<?= $uskin["id"] ?>">
                        <button>Upravit</button>
                    </form>
                    <form method="POST">
                        <input type="hidden" name="id" value="<?= $uskin["id"] ?>">
                        <button name="deleteuskin">Odstranit</button>
                    </form>
                </td>
                <!-- <?php } ?> -->
            </tr>
        <?php
            }
        ?>
    </tbody>


</table>